### ISSUE TITLE
keep-core CLI params and flags don't work

### ISSUE THREAD

**Issue by k0kk0k** [keep-network/keep-core#1579]
using of any flag or param shows error:
`Incorrect Usage. flag provided but not defined: -operators`
`22:27:50.935 CRITI  keep-main: flag provided but not defined: -operators main.go:77`

**Comment by Shadowfiend** [comment]
Trace here:
- We adjusted our approach to converting function names from Solidity to Go [here](https://github.com/keep-network/keep-common/commit/8ca95ff9de561f251db07c48cdcdfb76da079670#diff-10b1a8d2fcd46a80a34cd1e5bdf789c7L198) to align with go-ethereum's.
- In the process we hit every usage of the converted function name, including our subcommand generator's usage.
- The end result is that the *subcommands* for ethereum methods are now being prefixed by `-`.
- `urfave/cli`, the library we use for CLI definition and parsing, does *not* fail if subcommands prefixed by `-` are used. However, it *does* fail to recognize them; instead, it tries to recognize them as flags, and flags with that name have not been defined.

The correct solution here is *most likely* to remove most usages of `normalizedName` changed in the above commit, continuing to use the method name everywhere except for the `methodInfo`.

@pdyraga assigning this to you, but please feel free to reassign to someone else. This fix will land in `keep-common` rather than here, even though it was originally observed and reported in this repo, so if you prefer you can also transfer this issue to that repo.

**Comment by pdyraga** [comment]
Here is what happened:
- In https://github.com/keep-network/keep-common/commit/8ca95ff9de561f251db07c48cdcdfb76da079670#diff-10b1a8d2fcd46a80a34cd1e5bdf789c7L198 we introduced `toCamelCase` which normalizes function names using the same strategy as go-ethereum. This was needed so that we can have `__beaconCallback` function in `BondedECDSAKeepFactory`.
- `toCamelCase` uppercases the first letter, no matter if the function name starts with `_` or not. For example, `getGroupMembers` becomes `GetGroupMembers`.
- In `buildMethodInfo` we create `dashedName`:
    ```
    shortVarRegexp, err = regexp.Compile("([A-Z])[^A-Z]*")

    // (...)

	dashedName := strings.ToLower(string(shortVarRegexp.ReplaceAll(
		[]byte(normalizedName),
		[]byte("-$0"),
	)))
    ```

   Having the first letter upercase, `GetGroupMembers` becomes `-get-group-members`.


The fix is easy, we need to ensure the first letter stays lowercase during the normalization. Later, in `buildMethodInfo` we specify explicitly where do we want lowercase and uppercase with `uppercaseFirst` and `lowercaseFirst`.

I have the fix coded an tested. I'll open a PR to `keep-common` soon.
