### ISSUE TITLE
Minimum staking policy when establishing connection

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1588]
When two clients are about to connect with each other they execute a handshake. As a part of the handshake, they confirm the other peer has a minimum stake of KEEP. If not, handshake fails and the connection is not established. For every active connection, the minimum stake condition is monitored and if some client's minimum stake dropped below the required minimum, the connection is dropped.

It is all fine for beacon nodes. It may be problematic for ECDSA nodes. Even with a minimum stake, one client can participate in multiple keeps. If for one of those peers malicious signature is reported, client's stake is dropped to zero and all other clients will disconnect.

It means that for any other keep that client participates in as a signer, redemption is no longer possible.

There are two solutions:
- This is not a bug, it's a future. The malicious client is removed from the network. All keeps it participated in has to be liquidated
- We let that client remain in the network as long as it participates in some active keeps. Seems attractive, but that one malicious keep has nothing to lose but their bond. Not sure if this is enough collateral to prevent it from further misbehaving (e.g. trying to nuke some nodes).

I'd personally recommend the first option though there could be some implications I am not aware of.

**Comment by eth-r** [comment]
In bonded ECDSA the node should still have its bond for each keep. With how the bonded ECDSA incentives are designed, the bond should be sufficient to incentivize good behavior from participants.

Especially with 3-of-3 keeps, if one member is removed it prevents the entire keep from functioning. ECDSA keeps shouldn't be designed to rely on TBTC behavior to cover edge cases, or if they are, this should be clearly documented as a way the user of the keeps is expected to act. Other applications might have different needs, so I don't think it's necessary to create a cascading failure where it can be avoided. Not to mention, KEEP stake may be lost because of e.g. other members in a beacon group failing to generate their shares and the entire group timing out. Thus bonded ECDSA keeps should retain members that have gone below the minimum KEEP stake.

With Beacon the high safety factor should be sufficient to avoid this cascading failure mode. It also suggests that unbonded ECDSA keeps should only be used in a honest (super)majority mode instead of all-of-all.
