### ISSUE TITLE
Adjust DKG frequency

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1660]
Issue #1545 specifies that the DKG frequency should be of `1/20 ~ 1/30`. We will have this situation with DKG contribution margin set to 5% only when the actual gas is the same as gas price ceiling used for DKG contribution fee estimation.

With gas price set to `1Gwei` (same as Ropsten) we have DKG starting:
- 10 entries after genesis
- 5 entries after the previous DKG
- 1 entry after the previous DKG

See #1653

**Comment by eth-r** [comment]
5% gives 1/20 behavior in the worst-case scenario where all submitters use the maximum gas. If submitters use less gas we generate more groups and become time-constrained faster. Assuming money spent on ticket submission uses the same average gas price as DKG submission, this doesn't have unexpected adverse effects on staker finances which are calculated on a max-gas basis.

Normal gas costs tend to be in the range of 6~12 gwei, meaning that 1~2% would give expected behavior most of the time but increase the entry frequency required for the system to stay up without intervention by 2.5~5x in the worst-case. However, I don't think we necessarily need to change it as this higher rate of DKG just means that the average-case robustness of the beacon is better than the worst-case the parameters were calculated with.
