### ISSUE TITLE
Support viewing grants by ID without a paired wallet

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#1752]
Eg, dashboard.keep.network/grant/12345

Allowing anyone to view a grant will make management easier for custodians, as well as transparency with the greater community.

Note, it's still fine to lean on having a Web3 provider- we just don't want to require looking up whether someone has a particular grant to view a particular grant.

**Comment by liz-shinn** [comment]
What happens if you click on other parts of the token dash in the menu (are we showing the lefthand menu as dapp context)? If we showed the menu it would then redirect you to the paired wallet requirement screen.

View from Figma:
![Image 2020-05-18 at 11 52 58 AM](https://user-images.githubusercontent.com/57226633/82233572-39611400-98fe-11ea-93cd-c8fad6a3b6e6.png)
