### ISSUE TITLE
In the dashboard rewards tab should be possible to claim the rewards from all groups at once

### ISSUE THREAD

**Issue by shaimo** [keep-network/keep-core#1846]
I think this is the more probable use case. Why would anyone want to claim them just from a particular group? And right now you have to go one by one which is so tedious that I gave up...

**Comment by r-czajkowski** [comment]
The dashboard is limited by a smart contract. The `KeepRandomBeaconOperator` allows you to withdraw a reward for a given operator in a given group, pls see [here](https://github.com/keep-network/keep-core/blob/master/solidity/contracts/KeepRandomBeaconOperator.sol#L663).

**Comment by shaimo** [comment]
I don’t think the user should care about such technical/implementation limitations. Maybe there is some way to change the smartcontract code so it does allow accessing multiple groups at once? Doing it group by group makes zero sense usability wise...

**Comment by r-czajkowski** [comment]
I totally agree, but on the other side we are in the Ethereum world and every transaction costs gas. I'm concerned that function that allows you to withdraw all rewards at once might be too expensive due to [loop](https://github.com/keep-network/keep-core/blob/master/solidity/contracts/libraries/operator/Groups.sol#L318) and we should keep in mind an `out of gas` exception. cc @pdyraga

**Comment by shaimo** [comment]
I’m not an Ethereum expert but I don’t see how the gas will be more expensive than doing it one by one, as that wouldn’t make any sense. I assume mining a whole new transaction must be more expensive than one more iteration in an already running contract code...

**Comment by pdyraga** [comment]
Thanks for the issue @shaimo 🙌  Since we already have this discussion in #1841, please let me close this one and continue the conversation there.
