### ISSUE TITLE
Encryption of the ethereum password of the node

### ISSUE THREAD

**Issue by WayneWayner** [keep-network/keep-core#1905]
Since I am generally not a friend of storing private keys or passwords in clear text in files, it would be good if a solution could be found to store the password encrypted. In case of an attack it would be very easy to take over the account. 

I'm thinking of a process where the password is passed once by hand or even better with a hardware password manager (Ledger and Trezor can do that too) and then encrypted and stored by the keep client. 
Of course an encryption key is required for this. This key should not be available in clear text. You could either create one during runtime or store it in a build config and then exclude this build config from the repository.

**Comment by mhluongo** [comment]
The idea solving this at the client always sounds good, but the details sometimes make more secure deployments by professional more difficult- eg for a staker with 50 clients who auto-provisions keys. Further, operator keys *should only hold funds for gas* - the point of the delegation mechanism in the protocol is so a hacked operator key can only grief a staker rather than the hacker walking with funds, and not operator keys directly hold KEEP.

Do you have any examples of elegant solutions in clients with similar delegation mechanisms? Would be good to anchor the discussion.

**Comment by mhluongo** [comment]
If operator keys *are* going to be treated as special, rather than ephemeral.. as a Kubernetes guy, I'd typically want secrets in a key file or environment variable that's backed by a kube secret. Anyway, interested to hear ideas here that are compatible with that sort of deployment

**Comment by pdyraga** [comment]
The operator key is encrypted and all key shares are also encrypted. The password is provided as environment variable `KEEP_ETHEREUM_PASSWORD`.

Operator key:
https://github.com/keep-network/keep-core/blob/d5d192e678fb874329f33c7c1cdc130f2e83f173/cmd/start.go#L172-L175

Key shares:
https://github.com/keep-network/keep-core/blob/d5d192e678fb874329f33c7c1cdc130f2e83f173/cmd/start.go#L140-L143

Same for ECDSA client:
https://github.com/keep-network/keep-ecdsa/blob/563b3d698e07ddce8af97b455f94c5e494eb2fc8/cmd/start.go#L87-L90
https://github.com/keep-network/keep-ecdsa/blob/563b3d698e07ddce8af97b455f94c5e494eb2fc8/cmd/start.go#L148-L151

**Comment by mhluongo** [comment]
Closing this since it had already been addressed @WayneWayner. If you want to start a longer discussion in a new issue on client key security, we'd be interested in your thoughts!
