### ISSUE TITLE
(Mainnet) Contract transaction failed when I tried to delegate my grant on the dashboard

### ISSUE THREAD

**Issue by axone77** [keep-network/keep-core#1964]
#I use 3 differents addresses for maximum security, it dilutes the risks as much as possible. (Authorizer, Operator, Beneficiary). 

https://media.discordapp.net/attachments/717454156742393866/739498989782564864/Capture_decran_2020-08-02_a_17.04.47.png?width=2512&height=1269

My random beacon is setup and ready to run.

When delegating my stake and I confirm my transaction on metamask after having readjusted the gas fee correctly here is what, I get these errors :  

https://etherscan.io/tx/0x323ce60d7c31704f4562ff39ac43deae682159c0b218e0b8bf129a45d9b1793f

https://media.discordapp.net/attachments/717454156742393866/739998245752668273/Capture_decran_2020-07-26_a_21.02.15.png?width=2520&height=335 

I also tried to use an identical address for operator and authorizer but same issue.
Thanks in advance to those who have an idea, I may have missed something?

**Comment by pdyraga** [comment]
Thanks for opening the issue @axone77. I will look into it and report back.

**Comment by axone77** [comment]
Hi Pdyraga, any news for this issues ? You need some informations or can i retry to delegate from my mainnet dashboard ?

Thanks advance !

**Comment by pdyraga** [comment]
Hi @axone77, the grant manager did not authorize the staking contract. I think the reason was that we are starting to roll out a new staking contract version the next Monday. I recommend waiting for the official announcement and staking on the new contract. The old staking contract version will be deprecated and it doesn't make sense to lock your stake there.

**Comment by axone77** [comment]
Ok noted ! Thanks for your support !
