### ISSUE TITLE
Adding Keep to a delegation doesn't update balances

### ISSUE THREAD

**Issue by benlongstaff** [keep-network/keep-core#2092]
On the token dashboard, when adding keep to an existing delegation the transaction succeeds on chain but the balances of tokens and the percentages Staked do not update.

**Comment by r-czajkowski** [comment]
Hi! Thanks for reporting it.

Please see https://github.com/keep-network/keep-core/issues/1995#issuecomment-676056525 , maybe that's the point.

**Comment by benlongstaff** [comment]
@r-czajkowski there was indeed a section action to take under the top ups section

**Comment by r-czajkowski** [comment]
The `TokenStaking` contract adds a keep immediately in case when the delegation is in a `initializationPeriod` otherwise, the user needs to commit top up manually.

Please see
https://github.com/keep-network/keep-core/blob/cfbde62a2653091bfbba0e2edd685614af12aded/solidity/contracts/TokenStaking.sol#L258-L269
