### ISSUE TITLE
Reward pools should be visible before connecting a wallet

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#2239]

**Comment by liz-shinn** [comment]
Since this is someone who may not have KEEP tokens or LP Tokens, I think it makes sense on the version of this page before the wallet is connected that we link to an exchange and also link to each of the pools.

![Wallet Disconnected](https://user-images.githubusercontent.com/57226633/103327025-dd787500-4a20-11eb-9cc6-67cb482d33e1.png)
