### ISSUE TITLE
Disable the Beacon contract on the Applications page

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2297]
We should show a disabled state for the Beacon contract – currently the Authorize button is active and allows you to get to a transaction window with gas fees of $1000+ USD, no bueno.

<img width="347" alt="Screen Shot 2021-01-19 at 5 20 44 PM" src="https://user-images.githubusercontent.com/57226633/105100895-01f1cb00-5a7c-11eb-8bdb-6da4bced35c0.png">

**Comment by liz-shinn** [comment]
<img width="347" alt="Screen Shot 2021-01-19 at 5 20 44 PM" src="https://user-images.githubusercontent.com/57226633/105100989-2ea5e280-5a7c-11eb-94db-40620489f485.png">

Disable the "Authorize" button here ^^

**Comment by liz-shinn** [comment]
cc/ convo with @Battenfield 

1. Error in the contract, doesn't have enough gas to cover what it does cost
2. Whole thing blows up when the user doesn't have enough gas in their wallet to begin with for what it would cost
3. Is this is a MetaMask issue

![Screen Shot 2021-03-02 at 1 03 06 PM](https://user-images.githubusercontent.com/57226633/109693504-bb51bf00-7b57-11eb-849d-2fafaf437a90.png)

Course of action: 
1. If Metamask issue, then: 
-- we can render a model that says "This is an expensive transaction to authorize. please make sure you have enough ETH to cover the gas cost. If you don't have enough gas, MetaMask will show an incorrect balance usually of $1,000 or more."
-- when they reject the transaction then say "please make sure you have enough gas to cover which is xyz amount" but that shows an error when we don't know that's why they closed a transaction

2. If contract error, then the transaction will fail - MetaMask does the same thing
-- Then we would disable the button

**Comment by Battenfield** [comment]
- [ ] Spike out reason for the contract exception
    - [ ] Disable button if it's contract-related or design modal if it's just a lack of ETH issue

**Comment by Shadowfiend** [comment]
Sorry for not noticing this folks. The reason this transaction fails is that the random beacon operator contract has been panic buttoned (see https://docs.keep.network/random-beacon/#_the_registry_and_panic_button) due to issues from the November geth hard fork (see https://docs.keep.network/status-reports/2020-11-11-retro-geth-hardfork.html).

Disabling the authorize button, perhaps with a tooltip indicating the operator contract is disabled, or removing the beacon from the app list altogether, is a reasonable move. If we were to do the tooltip approach, we could probably generalize it by checking the registry to see if the contract is enabled and automatically disabling the button if it is not.
