### ISSUE TITLE
Could not put peer shares message to the evidence log

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3292]
When testing the client on commit 7fb579241eab388856f08ce0649a0071b48cf9d5 during the work on https://github.com/keep-network/keep-core/pull/3291 I noticed some problems in the beacon DKG, unrelated to the changes in that PR.

I was running 4 clients on M1 MacBook over the night.

Around 2022-09-21T04:37:40.701+0200, the first client started to log errors with the evidence log:

> 2022-09-21T04:37:40.701+0200	ERROR	keep-beacon	gjkr/protocol.go:321	could not put peer shares message to the evidence log: [message exists for sender 14] 

Similar problems were logged by the fourth client:

> 2022-09-21T04:37:41.453+0200	ERROR	keep-beacon	gjkr/protocol.go:321	could not put peer shares message to the evidence log: [message exists for sender 64] 

No problems like that were logged by the second and third client.

These problems lead to DKG failure on all four clients.

Example from the second client:

> 2022-09-21T04:48:14.735+0200	INFO	keep-beacon	result/signing.go:135	[member: 35] signature from sender [44] supports result different than preferred 

Logs:
- [client-1-new.txt](https://github.com/keep-network/keep-core/files/9614466/client-1-new.txt)
- [client-2-new.txt](https://github.com/keep-network/keep-core/files/9614470/client-2-new.txt)
- [client-3-new.txt](https://github.com/keep-network/keep-core/files/9614478/client-3-new.txt)
- [client-4-new.txt](https://github.com/keep-network/keep-core/files/9614482/client-4-new.txt)

**Comment by lukasz-zimnoch** [comment]
Some observations regarding the problem:

1. The `could not put peer shares message to the evidence log: [message exists for sender X]` error mentioned in the description also occurred on the private testnet (`keep-client-0` logs at `2022-09-22 19:24:02.443 CEST`). That means we are probably dealing with an old, quite rare, error as we didn't notice it before. Also, this error occurred on all clients mentioned in the description, not only the first and the fourth.
2. Occurrences of this error are surrounded by warnings about inactive members and `cannot find shares message from member X` errors. That means they are probably connected with themselves and are symptoms of a bigger problem
3. The `could not put peer shares message to the evidence log` error is not the direct cause of DKG failure. Members that log it do not abort execution and continue to operate normally. The DKG fails due to the small number of signatures that many inactive members cause. As stated in point 2, warnings about inactive members are probably connected with the error about the evidence log.

That said, a possible explanation of the observed behavior is as follows:

The problem starts in the most messages-heavy phase of DKG (shares & commitments). In this phase, each member produces two distinct messages, one with shares and one with commitments. We have `128` distinct messages in this phase. The phase takes `5` blocks so `5` retransmissions are done in total. The broadcast channel receive buffer for this phase has a size of `128`. If the `5` blocks go really quickly, it may happen that not all received messages are processed on time. It may also happen that multiple retransmissions of the same message land in the receive buffer and are processed by the protocol code (unlike ECDSA, the beacon DKG does not have message deduplication).  That means the possible outcomes of the commitment phase are:
- both shares and commitment messages from member X are missing -> member X is marked as inactive
- shares message from member X is received but commitment message is missing -> member X is marked as inactive
- commitment message from member X is received but shares message is missing -> member X is marked as inactive and `cannot find shares message from member X` is displayed
- more than one shares message from member X is received -> `could not put peer shares message to the evidence log: [message exists for sender X]` is displayed
- more than one commitment message from member X is received -> the latest message is taken into account
- one shares and one commitment message from member X is received -> happy path

The problem is hard to reproduce so this hypothesis cannot be immediately confirmed in an easy way. However, we can approach it in the following way:

1. Improve beacon DKG logging by adding DKG context and member index to the warnings and errors we are talking about here (currently they cannot be easily assigned to specific members). This will help with further debugging if the problem emerges again
2. Add message deduplication for beacon DKG just like we have in ECDSA DKG. This will eliminate `could not put peer shares messages to the evidence log: [message exists for sender X]` errors and protect us against weird corner cases that may occur when multiple messages from the given member are processed. This should also make the protocol more efficient as it will no longer lose time processing duplicated messages.
3. Think about making the commitment phase a little bit longer (8 blocks?). This way we increase the success chance of this phase where 128 messages must be handled instead of the usual 64. We don't need to do it immediately though.
